### ISSUE TITLE
regarding my repository fork

### ISSUE THREAD

**Issue by fheahdythdr** [nyulachan/nyula#1]
it's meant to be friends only, but i can't loadstring it without making it public, would you mind not forking the repository?

**Comment by fheahdythdr** [comment]
nevermind, changed my mind
i'm making it public

**Comment by nyulachan** [comment]
Sorry for not seeing this, I do not remember forking your repository. Sorry for any issues I have caused!

**Comment by fheahdythdr** [comment]
it's fine, i've made it public either way, so feel free to fork it now
